"""v0.6 渲染模块 — 从 orchestrator 提取

提供:
  - render_decision_card(card_dict, fmt, data_dir, task_id) → paths
  - render_scheme_report(state, fmt, data_dir) → paths (保留旧编排渲染)
"""

import json
from pathlib import Path
from datetime import datetime


def render_decision_card(card_dict: dict, fmt: str = "md",
                         data_dir=None, task_id: str = "") -> dict:
    """将 DecisionCard 渲染为文件

    Args:
        card_dict: DecisionCard.to_dict() 的输出
        fmt: "md" | "html" | "both"
        data_dir: 数据目录路径
        task_id: 任务ID

    Returns:
        {"format": str, "markdown": str, "html": str}
    """
    from src.models import DecisionCard
    card = DecisionCard.from_dict(card_dict)

    if data_dir is None:
        data_dir = Path("data")
    if isinstance(data_dir, str):
        data_dir = Path(data_dir)

    output_dir = data_dir / "outputs" / (task_id or card.task_id or card.card_id)
    output_dir.mkdir(parents=True, exist_ok=True)

    paths = {"format": fmt}

    if fmt in ("md", "both"):
        md_content = card.to_markdown()
        md_content += _render_checkpoint_details(card)
        md_path = output_dir / "decision_card.md"
        md_path.write_text(md_content, encoding="utf-8")
        paths["markdown"] = str(md_path)

    if fmt in ("html", "both"):
        html_content = _card_to_html(card)
        html_path = output_dir / "decision_card.html"
        html_path.write_text(html_content, encoding="utf-8")
        paths["html"] = str(html_path)

    return paths


def _render_checkpoint_details(card) -> str:
    """渲染检查点详细结果"""
    if not card.checkpoint_results:
        return ""
    lines = ["", "---", "", "## 检查点详细结果", ""]
    for r in card.checkpoint_results:
        lines.append(f"### {r.get('checkpoint_id', '?')}")
        lines.append(f"- 严重性: {r.get('severity', '?')}")
        lines.append(f"- 置信度: {r.get('confidence', 0):.0%}")
        lines.append(f"- 风险评分: {r.get('risk_score', 0):.1%}")
        lines.append(f"- LLM调用: {r.get('llm_calls', 0)}")
        if r.get("findings"):
            lines.append("- 发现:")
            for f in r["findings"]:
                lines.append(f"  - [{f.get('type','?')}] {f.get('detail','')}")
        if r.get("uncertainty_flags"):
            lines.append(f"- 不确定项: {'; '.join(str(u) for u in r['uncertainty_flags'][:5])}")
        lines.append("")
    return "\n".join(lines)


def _card_to_html(card) -> str:
    """DecisionCard 渲染为独立 HTML"""
    md_body = card.to_markdown()
    detail_md = _render_checkpoint_details(card)

    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>决策卡片: {card.task_summary or card.task[:60]}</title>
<style>
  body {{ font-family: -apple-system, sans-serif; max-width: 800px; margin: 0 auto;
         padding: 20px; background: #0f172a; color: #e2e8f0; line-height: 1.6; }}
  h1 {{ color: #6366f1; }}
  h2 {{ color: #94a3b8; border-bottom: 1px solid #334155; padding-bottom: 4px; }}
  h3 {{ color: #cbd5e1; }}
  .risk-low {{ color: #22c55e; }}
  .risk-medium {{ color: #eab308; }}
  .risk-high {{ color: #f97316; }}
  .risk-critical {{ color: #ef4444; }}
  ul {{ padding-left: 20px; }}
  li {{ margin: 6px 0; }}
  pre {{ background: #1e293b; padding: 12px; border-radius: 6px; overflow-x: auto; }}
  .meta {{ color: #64748b; font-size: 14px; }}
</style>
</head>
<body>
{_md_to_html(md_body)}
{_md_to_html(detail_md)}
<p class="meta">Generated by Collusion v0.6 Checkpoint Engine</p>
</body>
</html>"""


def _md_to_html(md: str) -> str:
    """简易 Markdown → HTML (不依赖 mistune)"""
    lines = md.split("\n")
    out = []
    in_list = False
    for line in lines:
        if line.startswith("## "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("### "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("# "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("- "):
            if not in_list:
                out.append("<ul>")
                in_list = True
            cls = ""
            if "BLOCKING" in line or "CRITICAL" in line:
                cls = ' class="risk-critical"'
            elif "WARNING" in line or "HIGH" in line:
                cls = ' class="risk-high"'
            out.append(f"<li{cls}>{line[2:]}</li>")
        elif line.startswith("---"):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append("<hr>")
        elif line.startswith("**") and "**" in line[2:]:
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<p><strong>{line[2:line.index('**', 2)]}</strong>{line[line.index('**', 2)+2:]}</p>")
        elif line.strip():
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<p>{line}</p>")
    if in_list:
        out.append("</ul>")
    return "\n".join(out)
